version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - /var/www/html/lojae-fe:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:5.6-fpm
        volumes:
            - /var/www/html/lojae-fe:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
